### ISSUE TITLE
Have any one meet this problem when "python train.py"?

### ISSUE THREAD

**Issue by Imalne** [TAMU-VITA/DeblurGANv2#34] opened 2019-12-05 09:38 UTC
Traceback (most recent call last):
  File "train.py", line 192, in <module>
    trainer.train()
  File "train.py", line 41, in train
    self._run_epoch(epoch)
  File "train.py", line 75, in _run_epoch
    loss_content = self.criterionG(outputs, targets)
  File "/home/a/DeblurGANv2/models/losses.py", line 63, in __call__
    return self.get_loss(fakeIm, realIm)
  File "/home/a/DeblurGANv2/models/losses.py", line 54, in get_loss
    fakeIm[0, :, :, :] = self.transform(fakeIm[0, :, :, :])
  File "/home/a/DeblurGANv2/venv/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/a/DeblurGANv2/venv/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: expected type torch.cuda.FloatTensor but got torch.FloatTensor

**Comment by wakanawakana** [comment] 2019-12-10 06:57
> File "train.py", line 192, in

There is no line 192 now

**Comment by 17666107783** [comment] 2019-12-17 10:14
I meet this problems too!

**Comment by 17666107783** [comment] 2019-12-17 11:08
I solved this problem! actually, this is error of pytorch, it should be : RuntimeError: expected type torch.FloatTensor but got torch.cuda.FloatTensor, so we can change the code models/loss.py line50-51 from 
        fakeIm[0, :, :, :] = self.transform(fakeIm[0, :, :, :])
        realIm[0, :, :, :] = self.transform(realIm[0, :, :, :])
to 
  `     fakeIm[0, :, :, :] = self.transform(fakeIm[0, :, :, :].data.cpu())
        realIm[0, :, :, :] = self.transform(realIm[0, :, :, :].data.cpu())`
it will be ok!

**Comment by 17666107783** [comment] 2019-12-17 11:08
I solved this problem! actually, this is error of pytorch, it should be : RuntimeError: expected type torch.FloatTensor but got torch.cuda.FloatTensor, so we can change the code models/loss.py line50-51 from 
        fakeIm[0, :, :, :] = self.transform(fakeIm[0, :, :, :])
        realIm[0, :, :, :] = self.transform(realIm[0, :, :, :])
to 
  `     fakeIm[0, :, :, :] = self.transform(fakeIm[0, :, :, :].data.cpu())
        realIm[0, :, :, :] = self.transform(realIm[0, :, :, :].data.cpu())`
it will be ok!

**Comment by lamia482** [comment] 2020-01-22 02:42
the root cause is that the torchvision viersion is Incompatible, just upgrade torchvision to 0.4.0 or above and pytorch correspondingly, in the new version, torchvision transformer(functional.py:215) has fix the bug

![image](https://user-images.githubusercontent.com/20201985/72861043-b3441080-3d03-11ea-8d8c-1427a344fe67.png)

**Comment by t-martyniuk** [comment] 2020-07-18 06:12
looks like the issue is not relevant anymore, closing

**Closed by t-martyniuk** 2020-07-18 06:12 UTC
